### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'ceil'

### ISSUE THREAD

**Issue by nitsanp** [onnx/onnx-tensorflow#454]
**Hi I'm trying to use**  ` from onnx_tf.backend import prepare` **to convert an onnx file to pb**

**(I'm using the latest versions of tensorflow and PyTorch because they support exporting last models to onnx. These are the versions I use:
tensorflow version: '2.0.0-beta1'
PyTorch version: '1.2.0a0+c9f41e9')
After I exported PyTorch to onnx, I try to export onnx to pb using your library and I get the following error:**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-6913ab77a9da> in <module>()
----> 1 from onnx_tf.backend import prepare

~/anaconda3/envs/tf_p36/lib/python3.6/site-packages/onnx_tf/__init__.py in <module>()
----> 1 from . import backend

~/anaconda3/envs/tf_p36/lib/python3.6/site-packages/onnx_tf/backend.py in <module>()
     26 from onnx_tf.common import get_device_option
     27 from onnx_tf.common import supports_device as common_supports_device
---> 28 from onnx_tf.common.handler_helper import get_all_backend_handlers
     29 from onnx_tf.pb_wrapper import OnnxNode
     30 

~/anaconda3/envs/tf_p36/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py in <module>()
      3 from onnx import defs
      4 
----> 5 from onnx_tf.handlers.backend import *  # noqa
      6 from onnx_tf.handlers.backend_handler import BackendHandler
      7 

~/anaconda3/envs/tf_p36/lib/python3.6/site-packages/onnx_tf/handlers/backend/ceil.py in <module>()
      8 
      9 @onnx_op("Ceil")
---> 10 @tf_func(tf.ceil)
     11 class Ceil(BasicMathMixin, BackendHandler):
     12 

**### AttributeError: module 'tensorflow' has no attribute 'ceil'**

**Comment by dnnagy** [comment]
I have the same issue with TF version 2.0.0-beta0:
```
>>> import onnx
>>> from onnx_tf.backend import prepare
/Users/nagydaniel/Documents/Munka/asseco/ml/notebooks/onnx-tensorflow/onnx_tf/common/__init__.py:87: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nagydaniel/Documents/Munka/asseco/ml/notebooks/onnx-tensorflow/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/Users/nagydaniel/Documents/Munka/asseco/ml/notebooks/onnx-tensorflow/onnx_tf/backend.py", line 28, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/Users/nagydaniel/Documents/Munka/asseco/ml/notebooks/onnx-tensorflow/onnx_tf/common/handler_helper.py", line 5, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/Users/nagydaniel/Documents/Munka/asseco/ml/notebooks/onnx-tensorflow/onnx_tf/handlers/backend/ceil.py", line 10, in <module>
    @tf_func(tf.ceil)
AttributeError: module 'tensorflow' has no attribute 'ceil'
```

I think it is because onnx-tensorflow is not compatible with tensorflow 2.

**Comment by fumihwh** [comment]
@nitsanp @dnnagy Yes. tf 2.0 changes lots of api...

**Comment by chinhuang007** [comment]
Thanks for reporting the tf 2.0 issue. A general issue is created to track the approach and progress of supporting Tensorflow 2.0, https://github.com/onnx/onnx-tensorflow/issues/460

**Comment by nitsanp** [comment]
Thank you!

**Comment by chinhuang007** [comment]
We support TF 2.0 now in the master branch! For TF 1.x please use the tf-1.x branch.

**Comment by aviaisr** [comment]
I still see this issue using the new version of onnx-tf.

**Comment by igormp** [comment]
Still able to reproduce this issue with the current master.
`pip install --user https://github.com/onnx/onnx-tensorflow/archive/master.zip`

**Comment by subhailams** [comment]
> Still able to reproduce this issue with the current master.
> `pip install --user https://github.com/onnx/onnx-tensorflow/archive/master.zip`

This works for me with TF 2.1

**Comment by igormp** [comment]
>This works for me with TF 2.1

Well, I'm on TF 2.2.0rc3 and Python 3.8 and still got:

```
>>> import onnx
>>> from onnx_tf.backend import prepare
2020-05-10 08:34:36.672472: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
/home/igor/.local/lib/python3.8/site-packages/onnx_tf/common/__init__.py:89: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/igor/.local/lib/python3.8/site-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/home/igor/.local/lib/python3.8/site-packages/onnx_tf/backend.py", line 29, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/home/igor/.local/lib/python3.8/site-packages/onnx_tf/common/handler_helper.py", line 5, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/home/igor/.local/lib/python3.8/site-packages/onnx_tf/handlers/backend/ceil.py", line 10, in <module>
    @tf_func(tf.ceil)
AttributeError: module 'tensorflow' has no attribute 'ceil'
```

Should I open a new issue?

**Comment by LukasMosser** [comment]
This does not work with TF 2.1 either also not from master.

**Comment by chinhuang007** [comment]
@LukasMosser @igormp When you see @tf_func(tf.ceil), it means you are using the ONNX-tf for TF 1.x. The master branch has @tf_func(tf.math.ceil), https://github.com/onnx/onnx-tensorflow/blob/9ed9bdc4b4ee27bb43cc8ad01645eb7c48572f7d/onnx_tf/handlers/backend/ceil.py#L10

In order to use the latest onnx-tf that support TF 2.x, please uninstall onnx-tf and build from source using the current master branch.

**Comment by igormp** [comment]
>In order to use the latest onnx-tf that support TF 2.x, please uninstall onnx-tf and build from source using the current master branch.

Running `pip uninstall onnx-tf` and then installing it again solved it for me. I guess I tried to install it from master previously without uninstalling the old version first.

**Comment by LukasMosser** [comment]
It has now worked for me as well, thanks.

**Comment by aish-where-ya** [comment]
Uninstall onnx-tf and run
`pip install git+https://github.com/onnx/onnx-tensorflow.git`

**Comment by geogeorgiev** [comment]
> Uninstall onnx-tf and run
> `pip install git+https://github.com/onnx/onnx-tensorflow.git`

Thank you! It worked for me -- `tensorflow 2.3` / python 3.8. In addition, I just needed to `pip install tensorflow-addons`.

**Comment by sai-sai-sai** [comment]
i solved this error by unistalling and installing . But i got a new error "cannot import name 'sys_config' from 'onnx_tf.common' "

**Comment by Adhithya-tech** [comment]
Now getting 'Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.' error

**Comment by chinhuang007** [comment]
This is a known limitation, as seen in notes section of https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status_v1_7_0.md.

**Comment by Adhithya-tech** [comment]
Any workaround @chinhuang007 ?

**Comment by chinhuang007** [comment]
Use one of the supported combinations as described status doc for resize in the onnx model. Or you are welcome to look into how to convert coordinate_transformation_mode=pytorch_half_pixel to Tensorflow implementation. Contributions are always highly appreciated!
